### ISSUE TITLE
Can I use jlink to debug MSP-EXP432P401R?

### ISSUE THREAD

**Issue by CHTUZKI** [zceemja/platform-timsp432#1]
HI.
I'm using platform-timsp432 in platformio IDE, everything works fine, but can't debug, can platform-timsp432 be debugged using jlink?

**Comment by zceemja** [comment]
Hello,

There is no debugger support added. I might investigate built-in xds110 debug probe in a couple of days, maybe it's easy to add. EnergyTrace would be nice to have too. Are you planning on using external jlink for debugging?

**Comment by zceemja** [comment]
Debugging should work now, test with 

[env:development]
platform = https://github.com/zceemja/platform-timsp432.git

if all good, I will push update to platformio

**Comment by CHTUZKI** [comment]
Thanks for your contribution. When my MSP-EXP432P401R express arrives in my hands, I will test the working of the onboard debugger

**Comment by CHTUZKI** [comment]
My MSP-EXP432P401R board arrived, but I found that the onboard xds110 of this board cannot be used, and windows cannot discover the device. So I can only debug with external jlink.
I want to get xds110 to work, it took me a long time, but it didn't work. I guess it may be that the MSP-EXP432P401R I bought is a pirated version and not an official TI board.
