### ISSUE TITLE
Debug the MSP-EXP432P401R using the onboard tools

### ISSUE THREAD

**Issue by CHTUZKI** [zceemja/platform-timsp432#2]
HI.
Ask this question again. I now have a board that can be debugged using the onboard tools. I now want to use XDS110 in platformio, how can I write platformio.ini

**Comment by zceemja** [comment]
Try:

```
[env:development]
platform = https://github.com/zceemja/platform-timsp432.git
board = lpmsp432p401r
framework = arduino
```
Check if it compiles and uploads basic code, then try adding breakpoints and "run and debug" in vscode

**Comment by CHTUZKI** [comment]
Not working. platformio tell me：

`Configuring upload protocol...`
`AVAILABLE: dslite`
`CURRENT: upload_protocol = dslite`
`Uploading .pio\build\lpmsp432p401r\firmware.elf`
`DSLite version 9.2.0.1793`
`Configuring Debugger (may take a few minutes on first launch)...`
 `       Initializing Register Database...`
`        Initializing: CS_DAP_0`
 `       Executing Startup Scripts: CS_DAP_0`
`        Initializing: CORTEX_M4_0`
`        Executing Startup Scripts: CORTEX_M4_0`
`Connecting...`
`GEL: CORTEX_M4_0: GEL Output: Memory Map Initialization Complete`
`GEL: CORTEX_M4_0: GEL Output: Halting Watchdog Timer`
`GEL: CORTEX_M4_0: WARNING   : On MSP432P401R hitting a breakpoint cannot be detected by the debugger when the device `is in low power mode.`
`                         Click the pause button during debug to check if the device is held at the breakpoint.`
`error: CORTEX_M4_0: Error initializing flash programming: Your XMS432P401R material is no longer supported. We recommend ``you moving to production-quality MSP432P401R/M silicon by ordering samples at www.ti.com/product/MSP432P401R.`
`Loading Program: .pio\build\lpmsp432p401r\firmware.elf`
`        Preparing ... `
`        .text: 0 of 150596 at 0x0`
`warning: CORTEX_M4_0: Loader: One or more sections of your program falls into a memory region that is not writable.  These ``regions will not actually be written to the target.  Check your linker configuration and/or memory map.`
`error: CORTEX_M4_0: File Loader: Verification failed: Values at address 0x00000000 do not match Please verify target memory` `and memory map.`
`        Finished`
`Failed: File: .pio\build\lpmsp432p401r\firmware.elf: a data verification error occurred, file load failed.`
`*** [upload] Error 1`

**Comment by zceemja** [comment]
Debug does not work with dslite uploader, with latest commit it should be set to openocd. Try adding in platformio.ini
```
upload_protocol = openocd
```
And make sure that `platform = https://github.com/zceemja/platform-timsp432.git`

**Comment by CHTUZKI** [comment]
I reinstalled the platform, uploaded with the default options, and now my XDS110 works, but I still get the error, the problem comes from the MCU。

```
Configuring upload protocol...
AVAILABLE: dslite
CURRENT: upload_protocol = dslite
Uploading .pio\build\lpmsp432p401r\firmware.elf
DSLite version 9.2.0.1793
Configuring Debugger (may take a few minutes on first launch)...
        Initializing Register Database...
        Initializing: CS_DAP_0
        Executing Startup Scripts: CS_DAP_0
        Initializing: CORTEX_M4_0
        Executing Startup Scripts: CORTEX_M4_0
Connecting...
GEL: CORTEX_M4_0: GEL Output: Memory Map Initialization Complete
GEL: CORTEX_M4_0: GEL Output: Halting Watchdog Timer
GEL: CORTEX_M4_0: WARNING   : On MSP432P401R hitting a breakpoint cannot be detected by the debugger when the device is in low power mode.
                         Click the pause button during debug to check if the device is held at the breakpoint.
error: CORTEX_M4_0: Error initializing flash programming: Your XMS432P401R material is no longer supported. We recommend you moving to production-quality MSP432P401R/M silicon by ordering samples at www.ti.com/product/MSP432P401R.
Loading Program: .pio\build\lpmsp432p401r\firmware.elf
        Preparing ... 
        .text: 0 of 150596 at 0x0
warning: CORTEX_M4_0: Loader: One or more sections of your program falls into a memory region that is not writable.  These regions will not actually be written to the target.  Check your linker configuration and/or memory map.
error: CORTEX_M4_0: File Loader: Verification failed: Values at address 0x00000000 do not match Please verify target memory and memory map.
        Finished
Failed: File: .pio\build\lpmsp432p401r\firmware.elf: a data verification error occurred, file load failed.
*** [upload] Error 1
```

My MCU seems to be locked, the problem is more complicated, I still haven't found a solution.😑😶😶😶😶😶😶😑😑
..

**Comment by zceemja** [comment]
There is something not right with your config. "CURRENT: upload_protocol = dslite" it should not be dslite. Can you send platformio.ini?

**Comment by CHTUZKI** [comment]
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lpmsp432p401r]
platform = timsp432
board = lpmsp432p401r
framework = tirtos
build_type = debug
build_flags = 
    -I .
    -I src\eeprom
    -I src\grbl
    -I src\keypad
    -I src\motors
    -I src\odometer
    -I src\plasma
    -I src\spindle
    -I src\spindle\vfd
    -I src\trinamic
    -I src

```

This is my PlatformIO.ini file, although there is a problem with my MCU, I feel that this configuration should work. I ordered an MCU again, and when this MCU arrives in my hands, I will test it again

**Comment by zceemja** [comment]
Replace 
`platform = timsp432`
with
`platform = https://github.com/zceemja/platform-timsp432.git`

**Comment by CHTUZKI** [comment]
Wow! Oh my God. It actually worked. I always thought it was something wrong with my chip. There are no problems now. Thank you very much

**Comment by zceemja** [comment]
Good to hear. I will upload update to platformio so that it would be sufficient to do this without the long link
